spring:
  application:
    name: PAYMENT-SERVICE
  zipkin:
    baseUrl: http://localhost:9411
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/data/payment_db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:9296

server:
  port: 8081
management:
  tracing:
    sampling:
      probability: 1.0
